spring:
  social:
    kakao:
      url: https://kapi.kakao.com/v2/user/me

  data:
    mongodb:
#      uri: mongodb://127.0.0.1:27017/sillog
      uri: mongodb+srv://haen:haen12@ala0.axbqe.mongodb.net/sillog?retryWrites=true&w=majority
jwt:
  secret: thisissecretwhichusedforsillogservicethisissecretwhichusedforsillogservice
